CREATE DATABASE COLLEGE;
CREATE DATABASE IF NOT EXISTS COLLEGE;
DROP DATABASE IF EXISTS company;
USE COLLEGE;
CREATE TABLE student (
id INT PRIMARY KEY, name VARCHAR(50),
age INT NOT NULL
);
INSERT INTO student VALUES (1, "AMAN", 26);
INSERT INTO student VALUES (1, "SHRADDHA", 26);

SELECT * FROM student;


DROP TABLE student;
USE COLLEGE;
CREATE TABLE STUDENT(
ROLLNO INT PRIMARY KEY,
NAME VARCHAR(50)
);
SELECT * FROM student;

INSERT INTO student
(ROLLNO, NAME)
VALUE
(101, "ARJUN"),
(102, "KARAN"),
(103,"RAM");

INSERT INTO student VALUE (104, "SHYAM"); #YOU CAN USE SINGLE LINE TO ADD SINGLE STUDENT DATA JUST U HAVE TO KNOW THE COLUMNS.

CREATE DATABASE XYZ;

USE XYZ;
CREATE TABLE EMPLOYEESINFO(
ID INT PRIMARY KEY,
NAME VARCHAR (100),
SALARY INT
);

INSERT INTO EMPLOYEESINFO
(ID, NAME, SALARY)
VALUES
(1, "ADAM", 25000),
(2, "BOB", 30000),
(3, "CASEY", 40000);

SELECT * FROM EMPLOYEESINFO;

CREATE TABLE TEMP1(
ID INT UNIQUE
);

INSERT INTO TEMP1 VALUES (101);
INSERT INTO TEMP1 VALUES (101);

SELECT * FROM TEMP1;

CREATE TABLE TEMP2(
ID INT,
NAME VARCHAR(50),
AGE INT,
CITY VARCHAR(20),
PRIMARY KEY (ID, NAME) #COMBINATIONS CANNOT BE SAME IF 101 - ADITYA THEN OTHER 101 - AKSHAY IT'S OKAY BUT 101 - ADITYA AGAIN IN THE ROW IS NOT APPLICABLE.
);

SELECT * FROM TEMP2;

#DEFAULT CONTRAINT
CREATE TABLE EMP(
ID INT,
SALARY INT DEFAULT 25000
);

INSERT INTO EMP(ID) VALUES (100);

SELECT * FROM EMP;

#CHECK CONSTRAINT

CREATE TABLE CITY (
ID INT PRIMARY KEY,
CITY VARCHAR (50),
AGE INT,
CONSTRAINT CHECK (AGE>=18 AND CITY="DELHI")
);

INSERT INTO CITY 
(ID, CITY, AGE) 
VALUES
(101, "MUMBAI", 24),
(102, "DELHI", 19),
(103, "KOLKATA", 19),
(104, "MUMBAI", 28),
(105, "DELHI", 17),
(106, "RATNAGIRI", 21);

---------------------------------------------------


