CREATE DATABASE SCHOOL;
USE SCHOOL;
CREATE TABLE STUDENT (
ID INT PRIMARY KEY, NAME VARCHAR(50)
);

INSERT INTO STUDENT
(ID, NAME)
VALUES
(101, "ADAM"),
(102, "BOB"),
(103, "CASEY");

CREATE TABLE COURSE (
ID INT PRIMARY KEY, 
COURSE VARCHAR(50)
);


INSERT INTO COURSE (ID, COURSE)
VALUES
(102, "ENGLISH"),
(105, "MATH'S"),
(103, "SCIENCE"),
(107, "COMPUTER SCIENCE");

#DROP TABLE STUDENT;
#DROP TABLE COURSE;

SELECT * FROM STUDENT;
SELECT * FROM COURSE;

#JOINS
#1. INNER JOIN:

SELECT *
FROM STUDENT AS S  #ALIAS NAME S (STUDENT) AND C (COURSE).
INNER JOIN COURSE AS C
ON S.ID = C.ID;

#2. LEFT JOIN:

SELECT *
FROM STUDENT AS S  #ALIAS NAME S (STUDENT) AND C (COURSE).
LEFT JOIN COURSE AS C
ON S.ID = C.ID;

#3. RIGHT JOIN:

SELECT *
FROM STUDENT AS S  #ALIAS NAME S (STUDENT) AND C (COURSE).
RIGHT JOIN COURSE AS C
ON S.ID = C.ID;

#4. FULL JOIN: USING UNION BETWEEN LEFT JOIN AND RIGHT JOIN.

SELECT *
FROM STUDENT AS S  #ALIAS NAME S (STUDENT) AND C (COURSE).
LEFT JOIN COURSE AS C
ON S.ID = C.ID
UNION  #MUST FOR FULL JOIN:
SELECT *
FROM STUDENT AS S  #ALIAS NAME S (STUDENT) AND C (COURSE).
RIGHT JOIN COURSE AS C
ON S.ID = C.ID;

#5. LEFT EXCLUSIVE JOIN:
SELECT *
FROM STUDENT AS S  #ALIAS NAME S (STUDENT) AND C (COURSE).
LEFT JOIN COURSE AS C
ON S.ID = C.ID
WHERE C.ID IS NULL;

#6. RIGHT EXCLUSIVE JOIN:

SELECT *
FROM STUDENT AS S  #ALIAS NAME S (STUDENT) AND C (COURSE).
RIGHT JOIN COURSE AS C
ON S.ID = C.ID
WHERE S.ID IS NULL;

#7. FULL EXCLUSIVE JOIN:

SELECT *
FROM STUDENT AS S  #ALIAS NAME S (STUDENT) AND C (COURSE).
LEFT JOIN COURSE AS C
ON S.ID = C.ID
WHERE C.ID IS NULL
UNION
SELECT *
FROM STUDENT AS S  #ALIAS NAME S (STUDENT) AND C (COURSE).
RIGHT JOIN COURSE AS C
ON S.ID = C.ID
WHERE S.ID IS NULL;

#8. SELF JOIN:

CREATE TABLE EMPLOYEE (
ID INT PRIMARY KEY, 
NAME VARCHAR(50),
MANAGER_ID INT
);

INSERT INTO EMPLOYEE (ID, NAME, MANAGER_ID)
VALUES
(101, "ADAM", 103),
(102, "BOB", 104),
(103, "CASEY", NULL),
(104, "DONALD", 103);

SELECT * FROM EMPLOYEE;

SELECT A.NAME AS MANAGER_NAME, B.NAME AS REPORTING_EMPLOYEE
FROM EMPLOYEE AS A
JOIN EMPLOYEE AS B
ON A.ID = B.MANAGER_ID;


#JOIN OPERATIONS:

SELECT NAME FROM EMPLOYEE
UNION ALL #GIVES DUPLICATE VALUES FROM BOTH THE TABLES.
SELECT NAME FROM EMPLOYEE;

